name: build

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive test-results
        if: always()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Test-Results
          path: core/build/reports/tests/allTests

      - name: Archive server log
        if: always()
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Server-Logs
          path: test-server/build/server.log

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Find
        run: find .

      - name: Install dependencies
        run: npm ci
        working-directory: ./headless-demo

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./headless-demo

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./headless-demo

      - name: Upload Playwright Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: headless-demo/playwright-report/
          retention-days: 30

      - name: Build with 11ty
        working-directory: ./www
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm install && npm run build

  update_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Dump API
        run: ./gradlew apiDump

      - name: Commit new API files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update API files
          file_pattern: "**/api/*.api"
