name: publish libs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive test-results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test-Results
        path: core/build/reports/tests/allTests

    - name: Archive server log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Server-Logs
        path: test-server/build/server.log

    - name: Publish with Gradle
      run: ./gradlew publish
      env: # Or as an environment variable
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}